version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "this is the test job"
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "this is the analyze job"


# Orchestrate our job run sequence
workflows:
  ci:
    jobs:
      - build
      - test
      - analyze